### ISSUE TITLE
Fix this color to white, as it it not visible clearly.

### ISSUE THREAD

**Issue by shivanshu-semwal** [kanakmi/kanakmi#1]
https://github.com/kanakmi/kanakmi/blob/d2750667c5e2dc0ab95b2b5a9eef864c9c033b37/main.css#L847

![image](https://user-images.githubusercontent.com/53912074/170524744-40af5f19-da2e-47aa-9aaa-001867bb662b.png)

**Comment by kanakmi** [comment]
Thanks Shivanshu. Fixed it 👍🏻.
